name: '[Auto] .github Sync'

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  GH_TOKEN: ${{ github.token }}  # For gh command
  WORKDIR: dot-github-sync
  TARGET_DIR: .github
  CENTRAL_REPO: ${{ github.repository_owner }}/.github

jobs:
  sync:
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            ${{ env.TARGET_DIR }}
          sparse-checkout-cone-mode: true

      - uses: actions/checkout@v6
        with:
          repository: ${{ env.CENTRAL_REPO }}
          path: ${{ env.WORKDIR }}
          sparse-checkout: |
            ${{ env.TARGET_DIR }}
          sparse-checkout-cone-mode: true

      - name: Commit + Push + Create PR
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          BRANCH="bot/${WORKDIR}"

          git pull

          # If remote branch exists → track it
          if git show-ref --verify --quiet "refs/remotes/origin/$BRANCH"; then
            git checkout -B "$BRANCH" "origin/$BRANCH"
          else
            git checkout -b "$BRANCH"
          fi

          # Sync all files (additive)
          mkdir -p "$TARGET_DIR"
          rsync -av "$WORKDIR/$TARGET_DIR/" "$TARGET_DIR/"

          git add "$TARGET_DIR"
          git diff --cached --quiet \
            && exit 0

          TS=$(date -u +"%Y%m%d-%H%M%S")

          git commit -m "[bot] Sync \`${TARGET_DIR}\` ($TS)"
          git push -u origin "$BRANCH"

          # Create PR only if one doesn't already exist
          if ! gh pr view "$BRANCH" >/dev/null 2>&1; then
            gh pr create \
              --head "$BRANCH" \
              --base main \
              --fill
          fi
