name: Test

on:
  #push:
  #  branches: [ main ]
  #  paths: [ 'src/**/*', 'test/**/*' ]
  #pull_request:
  #  branches: [ main ]
  #  paths: [ 'src/**/*', 'test/**/*' ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile  # Test requires dev deps
      - run: bun run test
      - run: bun run build
      - run: npm pack --dry-run 2>> $GITHUB_STEP_SUMMARY
