name: '[push,PR] Test Coverage'

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile --production

      - name: Run tests with coverage
        run: |
          bun test \
            --coverage \
            --coverage-reporter=text \
            --coverage-reporter=lcov  # Output path is hard-coded

      - name: Write coverage summary
        shell: bash
        run: |
          bun -e '
            const fs = require("fs");
            const raw = fs.readFileSync("coverage/lcov.info", "utf8");
            const records = raw.split("end_of_record");

            let md
              = "# 📊 Coverage Report\n"
              +"\n"
              + "| File | % Functions | % Lines | % Branches |\n"
              + "|:-----|------------:|--------:|-----------:|\n"
              ;

            for (const rec of records) {
              const lines = rec.trim().split("\n");

              let file = null;

              let lh = 0, lf = 0;
              let brh = 0, brf = 0;
              let fnh = 0, fnf = 0;

              for (const line of lines) {
                if (line.startsWith("SF:")) file = line.slice(3);

                if (line.startsWith("LH:")) lh += +line.slice(3);
                if (line.startsWith("LF:")) lf += +line.slice(3);

                if (line.startsWith("BRH:")) brh += +line.slice(4);
                if (line.startsWith("BRF:")) brf += +line.slice(4);

                if (line.startsWith("FNH:")) fnh += +line.slice(4);
                if (line.startsWith("FNF:")) fnf += +line.slice(4);
              }

              if (!file) continue;

              const pct = (hit, found) =>
                found === 0 ? "n/a" : ((hit / found) * 100).toFixed(2);

              md += `| ${file} | ${pct(fnh, fnf)} | ${pct(lh, lf)} | ${pct(brh, brf)} |\n`;
            }

            console.log(md);
          ' >> $GITHUB_STEP_SUMMARY
